# Generated by Django 5.0.6 on 2024-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_majorcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
    ]
