# Generated by Django 5.0.6 on 2024-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_tvets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvets',
            options={'verbose_name_plural': 'Tvets'},
        ),
    ]
