# Generated by Django 5.0.6 on 2024-05-11 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tvets_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/category/subcats')),
                ('location', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('bio', models.TextField(null=True)),
                ('date_of_birth', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tvets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tvets')),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
