# Generated by Django 5.0.6 on 2024-05-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
