# Generated by Django 5.0.6 on 2024-05-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_why_choose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Why_choose',
            new_name='WhyChoose',
        ),
    ]
